
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: jyoshise/testapp1
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: testapp1-service
  labels:
    app: app1
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    app: app1
