
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 3
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: jyoshise/testapp2
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: testapp1-service
  labels:
    app: app2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31001
  selector:
    app: app2
